site:
  title: 互联网计算机开发者文档
  start_page: docs::index.adoc
content:
  sources:
  - url: https://github.com/fifteen42/docs.git
    branches: main
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui
runtime:
  fetch: true
asciidoc:
  attributes:
    proglang: Motoko
    company-id: DFINITY
    toc: ~
    platform: Internet Computer platform
    IC: Internet Computer
    sdk-short-name: DFINITY Canister SDK
    sdk-long-name: DFINITY Canister Software Development Kit (SDK)
    # page-moc-version: 0.5.5
    # page-moc-base-tag: dfx-0.6.18